### ISSUE TITLE
Getting prettier-eslint errors

### ISSUE THREAD

**Issue by thgreasi** [resin-io-modules/resin-components#259]
Fresh `npm i` on master
> \> npm run prettify
```
Trace: prettier-eslint [TRACE]: requiring "prettier" module at "prettier"
    at Logger.trace (/home/teo/Resin.io/resin-components/node_modules/loglevel-colored-level-prefix/dist/index.js:54:24)
    at requireModule (/home/teo/Resin.io/resin-components/node_modules/prettier-eslint/dist/utils.js:433:12)
    at getPrettierConfig (/home/teo/Resin.io/resin-components/node_modules/prettier-eslint/dist/index.js:229:43)
    at format (/home/teo/Resin.io/resin-components/node_modules/prettier-eslint/dist/index.js:90:87)
    at MapSubscriber.project (/home/teo/Resin.io/resin-components/node_modules/prettier-eslint-cli/dist/format-files.js:305:55)
    at MapSubscriber._next (/home/teo/Resin.io/resin-components/node_modules/rxjs/operators/map.js:79:35)
    at MapSubscriber.Subscriber.next (/home/teo/Resin.io/resin-components/node_modules/rxjs/Subscriber.js:90:18)
    at AsyncSubject.Subject.next (/home/teo/Resin.io/resin-components/node_modules/rxjs/Subject.js:55:25)
    at AsyncSubject.complete (/home/teo/Resin.io/resin-components/node_modules/rxjs/AsyncSubject.js:46:35)
    at handlerFn (/home/teo/Resin.io/resin-components/node_modules/rxjs/observable/BoundNodeCallbackObservable.js:193:33)
    at tryToString (fs.js:457:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:444:12)
```

Explicitly using the previous `prettier-eslint-cli` (4.4.0) doesn't fix the issue. It looks like some of their dependencies didn't respect semver.

**Comment by LucianBuzzo** [comment]
@thgreasi can this be closed?

**Comment by thgreasi** [comment]
Oh yea, good catch, considered no longer applicable since #260
